---
include:
  - template: 'Security/License-Scanning.gitlab-ci.yml'
  - template: 'SAST.gitlab-ci.yml'
  - template: 'Dependency-Scanning.gitlab-ci.yml'
  - template: 'Code-Quality.gitlab-ci.yml'

variables:
  SAST_DISABLE_DIND: "true"
  DS_DISABLE_DIND: "true"
  MAVEN_CLI_OPTS: '-Dgpg.skip=true'

stages: [build, test, deploy]

cache:
  paths:
    - "$HOME/.m2/"

build:jdk8:
  image: maven:3-jdk-8
  stage: build
  script:
    - "mvn clean package -Dgpg.skip=true"
  artifacts:
    paths:
      - "target/*.jar"

build:jdk9:
  image: maven:3-jdk-9
  stage: build
  script:
    - "mvn clean package -Dgpg.skip=true"
  artifacts:
    paths:
      - "target/*.jar"

build:jdk11:
  image: maven:3-jdk-11
  stage: build
  script:
    - "mvn clean package -Dgpg.skip=true"
  artifacts:
    paths:
      - "target/*.jar"

build:jdk14:
  image: maven:3-jdk-14
  stage: build
  script:
    - "mvn clean package -Dgpg.skip=true"
  artifacts:
    paths:
      - "target/*.jar"

test:jdk8:
  image: maven:3-jdk-8
  stage: test
  needs:
    - job: build:jdk8
  script:
    - "mvn test -Dgpg.skip=true"

test:jdk9:
  image: maven:3-jdk-9
  stage: test
  needs:
    - job: build:jdk9
  script:
    - "mvn test -Dgpg.skip=true"

test:jdk11:
  image: maven:3-jdk-11
  stage: test
  needs:
    - job: build:jdk11
  script:
    - "mvn test -Dgpg.skip=true"

test:jdk14:
  image: maven:3-jdk-14
  stage: test
  needs:
    - job: build:jdk14
  script:
    - "mvn test -Dgpg.skip=true"

pages:
  image: maven:3-jdk-8
  stage: deploy
  script:
    - "mkdir .public"
    - "mvn javadoc:javadoc"
    - "cp -R target/site/apidocs/* .public/"
    - "mv .public public"
  artifacts:
    paths:
      - public
  only:
    - master
